set :domain, '159.65.22.44'
set :user, 'deploy'
set :application, 'Politics-In-Numbers'
set :repository, 'https://github.com/ForSetGeorgia/Politics-in-Numbers.git'
set :branch, 'master'
set :web_url, "pins.ge"
set :use_ssl, false
set :puma_thread_count_min, '1'
set :puma_thread_count_max, '4'
