set :domain, 'pins.ge'
set :user, 'pin'
set :application, 'Politics-In-Numbers'
set :repository, 'https://github.com/ForSetGeorgia/Politics-in-Numbers.git'
set :branch, 'embed'
set :web_url, "pins.ge"
set :use_ssl, true
set :puma_thread_count_min, '1'
set :puma_thread_count_max, '8'
